-- Superuser Setup for DDM Automation
-- Run these commands as a superuser or user with sys:secadmin role

-- 1. Grant sys:secadmin role to admin_user
GRANT ROLE sys:secadmin TO admin_user;

-- 2. Create masking function (if not exists)
CREATE OR REPLACE FUNCTION REDACT_SSN (ssn TEXT)
RETURNS TEXT IMMUTABLE
AS $$
    import re
    vSSN = ''.join(re.findall(r'\d+',ssn ))
    if len(vSSN)==9:
        rtn_val = 'xxx-xx-' + vSSN[5:9]
    else:
        rtn_val='invalid ssn'
    return rtn_val
$$ LANGUAGE plpythonu;

-- 3. Example masking policies (generated by automation)
-- Replace with actual output from automation script

-- For email column
CREATE MASKING POLICY mask_customer_e_mail_public
WITH (e_mail VARCHAR(256))
USING ('***MASKED***'::text);

ATTACH MASKING POLICY mask_customer_e_mail_public
ON customer(e_mail)
TO PUBLIC;

CREATE MASKING POLICY mask_customer_e_mail_analyst_role
WITH (e_mail VARCHAR(256))
USING (REGEXP_REPLACE(e_mail, '@.*', '@*****.com'));

ATTACH MASKING POLICY mask_customer_e_mail_analyst_role
ON customer(e_mail)
TO ROLE analyst_role
PRIORITY 10;

-- For SSN column
CREATE MASKING POLICY mask_customer_SSN_public
WITH (SSN VARCHAR(256))
USING ('XXX-XX-XXXX'::text);

ATTACH MASKING POLICY mask_customer_SSN_public
ON customer(SSN)
TO PUBLIC;

CREATE MASKING POLICY mask_customer_SSN_analyst_role
WITH (SSN VARCHAR(256))
USING (REDACT_SSN(SSN));

ATTACH MASKING POLICY mask_customer_SSN_analyst_role
ON customer(SSN)
TO ROLE analyst_role
PRIORITY 10;

CREATE MASKING POLICY mask_customer_SSN_admin_role
WITH (SSN VARCHAR(256))
USING (SSN);

ATTACH MASKING POLICY mask_customer_SSN_admin_role
ON customer(SSN)
TO ROLE admin_role
PRIORITY 20;